---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx-rc
  namespace: stg
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:stg-*
spec:
  releaseName: nginx-prod
  chart:
    git: git@github.com:pmquang/flux-get-started.git
    path: charts/nginx
    ref: master
  values:
    index: >-
      <h1>Hello</h1>
      <p>This is a stg</p>
    
    image: rai506/nginx:0.4.11
    replicaCount: 1
